# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import std_daq_service.writer_driver.start_stop.start_stop_writer_pb2 as start__stop__writer__pb2


class StartStopWriterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectDriver = channel.stream_stream(
                '/StartStopWriter/ConnectDriver',
                request_serializer=start__stop__writer__pb2.WriterRequest.SerializeToString,
                response_deserializer=start__stop__writer__pb2.WriterStatus.FromString,
                )


class StartStopWriterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectDriver(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StartStopWriterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectDriver': grpc.stream_stream_rpc_method_handler(
                    servicer.ConnectDriver,
                    request_deserializer=start__stop__writer__pb2.WriterRequest.FromString,
                    response_serializer=start__stop__writer__pb2.WriterStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StartStopWriter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StartStopWriter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectDriver(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/StartStopWriter/ConnectDriver',
            start__stop__writer__pb2.WriterRequest.SerializeToString,
            start__stop__writer__pb2.WriterStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
